apiVersion: apps/v1 
kind: Deployment
metadata:
  name: demo-api
spec: 
  selector:
    matchLabels:
      app: demo-api
  replicas: 2 # tells deployment to run 1 pod matching the template
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
      - name: demo-api
        image: gcr.io/dtc-attendee202/internal-image:v1.0.0
        env: 
        - name: dtc-attendee202
          value: "<project-id>"
        ports:
        - containerPort: 8082
            
        
